### ISSUE TITLE
新注册用户奖励

### ISSUE THREAD

**Issue by luckyyang** [open-archive/moooon-network#1]
新用户注册奖励规则：
- 使用推荐者链接：奖励200MNC
- 未使用推荐者链接：奖励100MNC

第二个规则我合同中忘记写了

**Comment by luckyyang** [comment]
commit信息也最好以issue number开头，如：#1 add user reward without referral link

**Comment by mypassword99** [comment]
好的，收到

**Comment by luckyyang** [comment]
@mypassword99 我更新了一下奖励的数字，最终的数字以这里为准

**Comment by mypassword99** [comment]
好的
