### ISSUE TITLE
6级奖励

### ISSUE THREAD

**Issue by luckyyang** [open-archive/moooon-network#2]
月球网采用邀请分级奖励规则，也就是你邀请来的人邀请了新的人，你仍然可以得到奖励的月球币，可以追溯你的 6 级人脉，获得月球币奖励:
- 一级用户 200 月球币
- 二级用户 100 月球币
- 三级用户 50 月球币
- 四级用户 30 月球币
- 五级用户 20 月球币
- 六级用户 10 月球币

**Comment by luckyyang** [comment]
@mypassword99 我更新了一下奖励的数字

**Comment by mypassword99** [comment]
ok
