### ISSUE TITLE
点开了失效链接的问题

### ISSUE THREAD

**Issue by mypassword99** [open-archive/moooon-network#3]
比如 “小王” 生成了一个链接，过了1天之后失效了，他把这个失效的链接分享给了”小李“  ，那么 ”小李“ 通过这个失效的链接注册后

1. 还属于 ”小王“ 下面的人吗？
2. 注册成功后，奖级按照什么规则算？是按照分享链接的注册的奖励算，还是按照没分享链接注册的奖励算？

**Comment by luckyyang** [comment]
这个逻辑就按照现在的逻辑算，应该是没有任何奖励了，因为已经失效了
