### ISSUE TITLE
针对需求有一个疑问，我复述一下，如有错误请纠正。

### ISSUE THREAD

**Issue by mypassword99** [open-archive/moooon-network#4]
比如，“小王” 是网站的用户，他生成了一个链接，分享给了”小张“ 

1. “小张” 注册后 “小王” 就能拿到相应的奖励对吗？？？

2. 对于小张来说，注册成功了自己也有奖励吗？？？
如果对于小张来说注册后有奖励：
  比如：”小张“ 是通过分享链接注册，那么”小张“ 会比没有分享链接注册，拿到的奖励多一些吗？？？

**Comment by luckyyang** [comment]
1. 是的
2. 小张使用小王的链接注册，小张的奖励就是会得到200MNC，同时小王也会得到200MNC的奖励；如果不用小王的链接注册，小张只得到100MNC的奖励

我说的清楚么？不清楚尽管问我

**Comment by mypassword99** [comment]
清楚，赞👍
